# Generated by Django 4.2.13 on 2024-07-25 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_and_exercises', '0003_quizquestion_section_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='TBC', max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='quizquestion',
            name='section_title',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='games_and_exercises.section'),
        ),
    ]
