# Generated by Django 4.2.13 on 2024-07-26 19:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_and_exercises', '0003_remove_choice_question_quizquestion_choices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='choices',
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='games_and_exercises.quizquestion'),
            preserve_default=False,
        ),
    ]
