# Generated by Django 4.2.13 on 2024-07-25 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_and_exercises', '0005_alter_quizquestion_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='section',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='games_and_exercises.section'),
        ),
    ]
