# Generated by Django 4.2.13 on 2024-07-30 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('games_and_exercises', '0005_remove_quizquestion_correct_choice_choice_is_correct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='is_correct',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='correct_choice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_for', to='games_and_exercises.choice'),
        ),
    ]
