# Generated by Django 4.2.13 on 2024-07-30 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games_and_exercises', '0006_remove_choice_is_correct_quizquestion_correct_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='correct_choice',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
    ]
