# Generated by Django 4.2.13 on 2024-07-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointment_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='surname',
            field=models.CharField(default='surname', max_length=100),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='email',
            field=models.EmailField(default='email', max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.TextField(default='message', max_length=1000),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='name',
            field=models.CharField(default='name', max_length=100),
        ),
    ]
