# Generated by Django 4.2.13 on 2024-08-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0006_alter_appointment_user_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.TextField(max_length=1000),
        ),
    ]
