# Generated by Django 4.2.13 on 2024-08-05 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_alter_appointment_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='message',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
